//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.PyramidWordServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PyramidWordServiceReference.IPyramidWordService")]
    public interface IPyramidWordService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPyramidWordService/IsPyramidWord", ReplyAction="http://tempuri.org/IPyramidWordService/IsPyramidWordResponse")]
        bool IsPyramidWord(string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPyramidWordService/IsPyramidWord", ReplyAction="http://tempuri.org/IPyramidWordService/IsPyramidWordResponse")]
        System.Threading.Tasks.Task<bool> IsPyramidWordAsync(string word);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPyramidWordServiceChannel : WCFClient.PyramidWordServiceReference.IPyramidWordService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PyramidWordServiceClient : System.ServiceModel.ClientBase<WCFClient.PyramidWordServiceReference.IPyramidWordService>, WCFClient.PyramidWordServiceReference.IPyramidWordService {
        
        public PyramidWordServiceClient() {
        }
        
        public PyramidWordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PyramidWordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PyramidWordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PyramidWordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsPyramidWord(string word) {
            return base.Channel.IsPyramidWord(word);
        }
        
        public System.Threading.Tasks.Task<bool> IsPyramidWordAsync(string word) {
            return base.Channel.IsPyramidWordAsync(word);
        }
    }
}
